# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../pyofx.ui'
#
# Created: Mon Oct  4 13:50:33 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(588, 403)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fi_label = QtGui.QLabel(self.centralwidget)
        self.fi_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fi_label.setWordWrap(True)
        self.fi_label.setObjectName("fi_label")
        self.horizontalLayout_2.addWidget(self.fi_label)
        self.fi = QtGui.QComboBox(self.centralwidget)
        self.fi.setObjectName("fi")
        self.horizontalLayout_2.addWidget(self.fi)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.request = QtGui.QGroupBox(self.centralwidget)
        self.request.setFlat(False)
        self.request.setObjectName("request")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.request)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.statement = QtGui.QRadioButton(self.request)
        self.statement.setChecked(True)
        self.statement.setObjectName("statement")
        self.horizontalLayout_3.addWidget(self.statement)
        self.dry_run = QtGui.QRadioButton(self.request)
        self.dry_run.setObjectName("dry_run")
        self.horizontalLayout_3.addWidget(self.dry_run)
        self.profile = QtGui.QRadioButton(self.request)
        self.profile.setObjectName("profile")
        self.horizontalLayout_3.addWidget(self.profile)
        self.horizontalLayout_4.addWidget(self.request)
        self.download = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.download.setFont(font)
        self.download.setObjectName("download")
        self.horizontalLayout_4.addWidget(self.download)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.tabs = QtGui.QTabWidget(self.centralwidget)
        self.tabs.setObjectName("tabs")
        self.fi_tab = QtGui.QWidget()
        self.fi_tab.setObjectName("fi_tab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.fi_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.url_label = QtGui.QLabel(self.fi_tab)
        self.url_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.url_label.setObjectName("url_label")
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.url_label)
        self.url = QtGui.QLineEdit(self.fi_tab)
        self.url.setObjectName("url")
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.url)
        self.verticalLayout_2.addLayout(self.formLayout_6)
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.org_label = QtGui.QLabel(self.fi_tab)
        self.org_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.org_label.setObjectName("org_label")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.org_label)
        self.org = QtGui.QLineEdit(self.fi_tab)
        self.org.setObjectName("org")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.org)
        self.fid_label = QtGui.QLabel(self.fi_tab)
        self.fid_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fid_label.setObjectName("fid_label")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.fid_label)
        self.fid = QtGui.QLineEdit(self.fi_tab)
        self.fid.setObjectName("fid")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.fid)
        self.bankid_label = QtGui.QLabel(self.fi_tab)
        self.bankid_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.bankid_label.setObjectName("bankid_label")
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.bankid_label)
        self.bankid = QtGui.QLineEdit(self.fi_tab)
        self.bankid.setObjectName("bankid")
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.bankid)
        self.brokerid_label = QtGui.QLabel(self.fi_tab)
        self.brokerid_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.brokerid_label.setObjectName("brokerid_label")
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.brokerid_label)
        self.brokerid = QtGui.QLineEdit(self.fi_tab)
        self.brokerid.setObjectName("brokerid")
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.brokerid)
        self.verticalLayout_2.addLayout(self.formLayout_5)
        self.compat = QtGui.QGroupBox(self.fi_tab)
        self.compat.setObjectName("compat")
        self.horizontalLayout = QtGui.QHBoxLayout(self.compat)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.appid_label = QtGui.QLabel(self.compat)
        self.appid_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.appid_label.setObjectName("appid_label")
        self.horizontalLayout.addWidget(self.appid_label)
        self.appid = QtGui.QComboBox(self.compat)
        self.appid.setObjectName("appid")
        self.horizontalLayout.addWidget(self.appid)
        self.appver_label = QtGui.QLabel(self.compat)
        self.appver_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.appver_label.setObjectName("appver_label")
        self.horizontalLayout.addWidget(self.appver_label)
        self.appver = QtGui.QComboBox(self.compat)
        self.appver.setObjectName("appver")
        self.horizontalLayout.addWidget(self.appver)
        self.version_label = QtGui.QLabel(self.compat)
        self.version_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.version_label.setObjectName("version_label")
        self.horizontalLayout.addWidget(self.version_label)
        self.version = QtGui.QComboBox(self.compat)
        self.version.setObjectName("version")
        self.horizontalLayout.addWidget(self.version)
        self.verticalLayout_2.addWidget(self.compat)
        self.tabs.addTab(self.fi_tab, "")
        self.acct_tab = QtGui.QWidget()
        self.acct_tab.setObjectName("acct_tab")
        self.verticalLayout = QtGui.QVBoxLayout(self.acct_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.user_label = QtGui.QLabel(self.acct_tab)
        self.user_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.user_label.setObjectName("user_label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.user_label)
        self.user = QtGui.QLineEdit(self.acct_tab)
        self.user.setObjectName("user")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.user)
        self.verticalLayout.addLayout(self.formLayout)
        self.bank = QtGui.QGroupBox(self.acct_tab)
        self.bank.setFlat(False)
        self.bank.setCheckable(False)
        self.bank.setObjectName("bank")
        self.formLayout_2 = QtGui.QFormLayout(self.bank)
        self.formLayout_2.setObjectName("formLayout_2")
        self.checking_label = QtGui.QLabel(self.bank)
        self.checking_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checking_label.setObjectName("checking_label")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.checking_label)
        self.checking = QtGui.QLineEdit(self.bank)
        self.checking.setObjectName("checking")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.checking)
        self.savings_label = QtGui.QLabel(self.bank)
        self.savings_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.savings_label.setObjectName("savings_label")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.savings_label)
        self.savings = QtGui.QLineEdit(self.bank)
        self.savings.setObjectName("savings")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.savings)
        self.moneymrkt_label = QtGui.QLabel(self.bank)
        self.moneymrkt_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.moneymrkt_label.setObjectName("moneymrkt_label")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.moneymrkt_label)
        self.moneymrkt = QtGui.QLineEdit(self.bank)
        self.moneymrkt.setObjectName("moneymrkt")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.moneymrkt)
        self.creditline_label = QtGui.QLabel(self.bank)
        self.creditline_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.creditline_label.setObjectName("creditline_label")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.creditline_label)
        self.creditline = QtGui.QLineEdit(self.bank)
        self.creditline.setObjectName("creditline")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.creditline)
        self.verticalLayout.addWidget(self.bank)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.creditcard_label = QtGui.QLabel(self.acct_tab)
        self.creditcard_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.creditcard_label.setObjectName("creditcard_label")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.creditcard_label)
        self.creditcard = QtGui.QLineEdit(self.acct_tab)
        self.creditcard.setObjectName("creditcard")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.creditcard)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.investment_label = QtGui.QLabel(self.acct_tab)
        self.investment_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.investment_label.setObjectName("investment_label")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.investment_label)
        self.investment = QtGui.QLineEdit(self.acct_tab)
        self.investment.setObjectName("investment")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.investment)
        self.verticalLayout.addLayout(self.formLayout_4)
        self.tabs.addTab(self.acct_tab, "")
        self.stmt_tab = QtGui.QWidget()
        self.stmt_tab.setObjectName("stmt_tab")
        self.layoutWidget = QtGui.QWidget(self.stmt_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 20, 514, 60))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.inctran = QtGui.QCheckBox(self.layoutWidget)
        self.inctran.setObjectName("inctran")
        self.gridLayout.addWidget(self.inctran, 0, 0, 1, 1)
        self.dtstart_label = QtGui.QLabel(self.layoutWidget)
        self.dtstart_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.dtstart_label.setObjectName("dtstart_label")
        self.gridLayout.addWidget(self.dtstart_label, 0, 1, 1, 1)
        self.dtstart = QtGui.QDateTimeEdit(self.layoutWidget)
        self.dtstart.setCalendarPopup(True)
        self.dtstart.setObjectName("dtstart")
        self.gridLayout.addWidget(self.dtstart, 0, 2, 1, 1)
        self.dtend_label = QtGui.QLabel(self.layoutWidget)
        self.dtend_label.setEnabled(True)
        self.dtend_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.dtend_label.setObjectName("dtend_label")
        self.gridLayout.addWidget(self.dtend_label, 0, 3, 1, 1)
        self.dtend = QtGui.QDateTimeEdit(self.layoutWidget)
        self.dtend.setEnabled(True)
        self.dtend.setCalendarPopup(True)
        self.dtend.setObjectName("dtend")
        self.gridLayout.addWidget(self.dtend, 0, 4, 1, 1)
        self.incpos = QtGui.QCheckBox(self.layoutWidget)
        self.incpos.setObjectName("incpos")
        self.gridLayout.addWidget(self.incpos, 1, 0, 1, 1)
        self.dtasof_label = QtGui.QLabel(self.layoutWidget)
        self.dtasof_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.dtasof_label.setObjectName("dtasof_label")
        self.gridLayout.addWidget(self.dtasof_label, 1, 1, 1, 1)
        self.dtasof = QtGui.QDateTimeEdit(self.layoutWidget)
        self.dtasof.setCalendarPopup(True)
        self.dtasof.setObjectName("dtasof")
        self.gridLayout.addWidget(self.dtasof, 1, 2, 1, 1)
        self.incbal = QtGui.QCheckBox(self.layoutWidget)
        self.incbal.setObjectName("incbal")
        self.gridLayout.addWidget(self.incbal, 1, 3, 1, 2)
        self.tabs.addTab(self.stmt_tab, "")
        self.verticalLayout_3.addWidget(self.tabs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 588, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConfig = QtGui.QAction(MainWindow)
        self.actionConfig.setObjectName("actionConfig")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionTest = QtGui.QAction(MainWindow)
        self.actionTest.setObjectName("actionTest")
        self.menuFile.addAction(self.actionConfig)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.fi_label.setBuddy(self.fi)
        self.url_label.setBuddy(self.url)
        self.org_label.setBuddy(self.org)
        self.fid_label.setBuddy(self.fid)
        self.bankid_label.setBuddy(self.bankid)
        self.brokerid_label.setBuddy(self.brokerid)
        self.appid_label.setBuddy(self.appid)
        self.appver_label.setBuddy(self.appver)
        self.version_label.setBuddy(self.version)
        self.user_label.setBuddy(self.user)
        self.checking_label.setBuddy(self.checking)
        self.savings_label.setBuddy(self.savings)
        self.moneymrkt_label.setBuddy(self.moneymrkt)
        self.creditline_label.setBuddy(self.creditline)
        self.creditcard_label.setBuddy(self.creditcard)
        self.investment_label.setBuddy(self.investment)
        self.dtstart_label.setBuddy(self.dtstart)
        self.dtend_label.setBuddy(self.dtend)
        self.dtasof_label.setBuddy(self.dtasof)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PyOFX", None, QtGui.QApplication.UnicodeUTF8))
        self.fi_label.setText(QtGui.QApplication.translate("MainWindow", "Financial Institution", None, QtGui.QApplication.UnicodeUTF8))
        self.request.setTitle(QtGui.QApplication.translate("MainWindow", "Request", None, QtGui.QApplication.UnicodeUTF8))
        self.statement.setText(QtGui.QApplication.translate("MainWindow", "Statement", None, QtGui.QApplication.UnicodeUTF8))
        self.dry_run.setText(QtGui.QApplication.translate("MainWindow", "Dry run", None, QtGui.QApplication.UnicodeUTF8))
        self.profile.setText(QtGui.QApplication.translate("MainWindow", "Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.download.setText(QtGui.QApplication.translate("MainWindow", "Download", None, QtGui.QApplication.UnicodeUTF8))
        self.url_label.setText(QtGui.QApplication.translate("MainWindow", "URL", None, QtGui.QApplication.UnicodeUTF8))
        self.org_label.setText(QtGui.QApplication.translate("MainWindow", "ORG", None, QtGui.QApplication.UnicodeUTF8))
        self.fid_label.setText(QtGui.QApplication.translate("MainWindow", "FID", None, QtGui.QApplication.UnicodeUTF8))
        self.bankid_label.setText(QtGui.QApplication.translate("MainWindow", "Bank ID", None, QtGui.QApplication.UnicodeUTF8))
        self.brokerid_label.setText(QtGui.QApplication.translate("MainWindow", "Broker ID", None, QtGui.QApplication.UnicodeUTF8))
        self.compat.setTitle(QtGui.QApplication.translate("MainWindow", "Compatibility", None, QtGui.QApplication.UnicodeUTF8))
        self.appid_label.setText(QtGui.QApplication.translate("MainWindow", "APPID", None, QtGui.QApplication.UnicodeUTF8))
        self.appver_label.setText(QtGui.QApplication.translate("MainWindow", "APPVER", None, QtGui.QApplication.UnicodeUTF8))
        self.version_label.setText(QtGui.QApplication.translate("MainWindow", "VERSION", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.fi_tab), QtGui.QApplication.translate("MainWindow", "Firm", None, QtGui.QApplication.UnicodeUTF8))
        self.user_label.setText(QtGui.QApplication.translate("MainWindow", "User ID", None, QtGui.QApplication.UnicodeUTF8))
        self.bank.setTitle(QtGui.QApplication.translate("MainWindow", "Bank", None, QtGui.QApplication.UnicodeUTF8))
        self.checking_label.setText(QtGui.QApplication.translate("MainWindow", "Checking", None, QtGui.QApplication.UnicodeUTF8))
        self.savings_label.setText(QtGui.QApplication.translate("MainWindow", "Savings", None, QtGui.QApplication.UnicodeUTF8))
        self.moneymrkt_label.setText(QtGui.QApplication.translate("MainWindow", "Money Market", None, QtGui.QApplication.UnicodeUTF8))
        self.creditline_label.setText(QtGui.QApplication.translate("MainWindow", "Credit Line", None, QtGui.QApplication.UnicodeUTF8))
        self.creditcard_label.setText(QtGui.QApplication.translate("MainWindow", "Credit Card", None, QtGui.QApplication.UnicodeUTF8))
        self.investment_label.setText(QtGui.QApplication.translate("MainWindow", "Investment", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.acct_tab), QtGui.QApplication.translate("MainWindow", "Accounts", None, QtGui.QApplication.UnicodeUTF8))
        self.inctran.setText(QtGui.QApplication.translate("MainWindow", "INCTRAN", None, QtGui.QApplication.UnicodeUTF8))
        self.dtstart_label.setText(QtGui.QApplication.translate("MainWindow", "DTSTART", None, QtGui.QApplication.UnicodeUTF8))
        self.dtend_label.setText(QtGui.QApplication.translate("MainWindow", "DTEND", None, QtGui.QApplication.UnicodeUTF8))
        self.incpos.setText(QtGui.QApplication.translate("MainWindow", "INCPOS", None, QtGui.QApplication.UnicodeUTF8))
        self.dtasof_label.setText(QtGui.QApplication.translate("MainWindow", "DTASOF", None, QtGui.QApplication.UnicodeUTF8))
        self.incbal.setText(QtGui.QApplication.translate("MainWindow", "INCBAL", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.stmt_tab), QtGui.QApplication.translate("MainWindow", "Statement", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfig.setText(QtGui.QApplication.translate("MainWindow", "Load Config", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfig.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTest.setText(QtGui.QApplication.translate("MainWindow", "Test", None, QtGui.QApplication.UnicodeUTF8))

