name: CI tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install -e ".[net,dev]"
    - name: Lint with ruff
      run: ruff check
    - name: Check formatting with ruff
      run: ruff format --check
    - name: Static analysis with mypy
      run: mypy
    - name: Run tests
      run: pytest --cov-report lcov:coverage.lcov --cov=ofxtools tests/
    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        path-to-lcov: coverage.lcov
